### ISSUE TITLE
Error in NodeJS when trying to access variable 'document'

### ISSUE THREAD

**Issue by andre-f-paggi** [guillaumepotier/gettext.js#13]
Even after the PR #10, it is still generating an error when using this library on NodeJs environment:

> ReferenceError: document is not defined
> at i18n (\node_modules\gettext.js\lib\gettext.js:10:15)

> PS: I pasted the new code on the `node_modules` folder since the newest version is not on NPM yet.

If I check for `this.document` instead of `document `directly seems that solves the problem.

**Comment by guillaumepotier** [comment]
Ok then,

Feel free to submit a new PR then :)

Best
