### ISSUE TITLE
why not the method that get messages?

### ISSUE THREAD

**Issue by peigong** [guillaumepotier/gettext.js#25]
hi, I need a method that get the_dictionary. so, I may add a message to _dictionary. the getMessages is setMessages brother, why not? may I commit a PR for this?

**Comment by guillaumepotier** [comment]
Hi there,

I don't think it is a good thing to "expose" the dictionary to the outside world. When I created this lib, I had no other usage than loading just once all the translations and keys.

Maybe if there is an usage for that, you could work on a PR that adds two or three methods:

`i18n.getMessage(key, [domain], [locale])`
`i18n.setMessage(key, translation, [domain], [locale])` 
`i18n.removeMessage(key, translation, [domain], [locale])`

where domain and locale are facultative (if not provided, use the current ones).

But you could also update your messages catalog by replacing the existing one by a new one containing one or two more keys, that would work too.

The aim here is really to keep the lib simple and short, lightweight.

What is your use case really?

Best

**Comment by peigong** [comment]
Keep the lib simple and short, lightweight. Very nice! 
I may fork this lib for my project.
My project so big. So, I think that split the messages. When need, so load.
Thank you very much!
