### ISSUE TITLE
Fallback behaviour doesn't work when a context is provided

### ISSUE THREAD

**Issue by chrisnicola** [guillaumepotier/gettext.js#27]
Because a context msgid typically looks like this: `context\u0004translate this` the default fallback behaviour to simply return the msgid produces the unexpected result of returning the context again.

It would be idea if the context and delimiter was stripped out before returning the text.

**Comment by guillaumepotier** [comment]
Hi there,

Thanks for the info. Could you have a look at https://github.com/guillaumepotier/gettext.js/pull/28 and tell me if that's you're looking for?

Best

**Comment by chrisnicola** [comment]
@guillaumepotier yes that looks about right to me.

**Comment by guillaumepotier** [comment]
Awesome ! I'm merging it and releasing it. Best

**Comment by guillaumepotier** [comment]
Fixed and released. Best
