### ISSUE TITLE
node chokes on export in lib/gettext.js

### ISSUE THREAD

**Issue by mmomtchev** [guillaumepotier/gettext.js#30]
node 12 will choke on the export statement in lib/gettext.js (as require will include the main from the package.json)

my workaround is to require the CommonJS file :

const i18n = require('gettext.js/dist/gettext.cjs.min.js');

#31

**Comment by guillaumepotier** [comment]
Merged! (Did not had time to test bower. I saw that it was now deprecated so not really a concern anymore)

Thanks for your work
