### ISSUE TITLE
Wrong (or not so accurate) documentation

### ISSUE THREAD

**Issue by cnaaq** [guillaumepotier/gettext.js#44]
The documentation mentioned for using the `gettext.js` in the browser is not working,
It returns the `Unexpected token 'export'`.

I also tried to use use `require`  and use some bundler like `webpack` or `browserify`, however, that didn't work as well.

Am I missing something?

**Comment by Artoria2e5** [comment]
Yeah, the lib is written using ESM, so it's... no longer supposed to be used that way. Use the IIFE version in dist.

**Comment by hokascha** [comment]
this should be made clear in the docs!

**Comment by Artoria2e5** [comment]
It's in #50.

**Comment by guillaumepotier** [comment]
Thanks @Artoria2e5, I've merged your PR.

Best
