### ISSUE TITLE
[feat] Comments and References

### ISSUE THREAD

**Issue by jarodium** [guillaumepotier/gettext.js#46]
Hello

Would you consider adding support to comments and references?

I am aware this support to comments and references will make the file larger, but a separate json file " comments.json " and "references.json" to match the translations.

There may be advantages for user interfaces that may want to edit the json directly, without loading the PO file directly, like my use case.

Thank you

**Comment by guillaumepotier** [comment]
I don't see any inconvenience shipping comments and refs into the json dictionary file. But unless I'm mistaking, this has nothing to do really with gettext.js? Its sole purpose is to read a dic file and translate strings with plural forms. gettext.js should be comments and references agnostic no?

So I'm not properly understanding your issue/feature request? Could you please elaborate?

Best

**Comment by jarodium** [comment]
Yes you are right. It doesn't.
This lib handles the files as if they were .mo files and not .po files.

But I thought if a translator goes straight to this file and does not see any comments or references, it may be trouble for him to translate something directly in this file.

In my own use case, I make use of both .mo and .json files.
I use gettext.js to handle translations only for JS and I have the php gettext to handle translations for PHP scripts.
I have a small homebrewed editor that allows me to update both PO and JSON files ( adding comments and references to both files ). 
The JS portion of my webapp, may not use the same translations as the PO, and that's the reason I don't reuse a po file to generate the JSON.

My goal is to give my users the ability to translate themselves parts of the website and add comments without breaking the plugin.

I'm not able to use a PO Converter ( hosting does not allow binaries to run ) and don't want to have a po file dedicated to the JS portion of the website and use it to convert it to JSON. If I could skip that step would be great.

Thank you for you time
Best regards

**Comment by guillaumepotier** [comment]
Feel free to create a separate project for that matter, I'd gladly add it
to Readme.md if useful in combination with gettext.js :)

Best

[image: Capture d’écran 2020-04-16 à 14.00.24.png]


Guillaume Potier

Fondateur


*guillaume@wisembly.com <guillaume@wisembly.com>*
+33 6 70 52 81 08
[image: logo]
<https://www.linkedin.com/company/wisembly/?viewAsMember=true>
<https://twitter.com/wisembly> <https://www.facebook.com/Wisembly>
www.wisembly.com
<https://tracking.vocus.io/link?id=ed236db3-e558-451e-af56-296a33ce0148&url=https%3A%2F%2Ftracking.vocus.io%2Flink%3Fid%3D9bdeb7d8-0051-4763-8f89-71ef082dd143%26url%3Dhttps%253A%252F%252Ftracking.vocus.io%252Flink%253Fid%253D53d6ae7d-781e-4006-a9bb-022a73afbcc5%2526url%253Dhttp%25253A%25252F%25252Fwww.wisembly.com>



Le jeu. 11 févr. 2021 à 20:50, Pedro Heliodoro <notifications@github.com> a
écrit :
