### ISSUE TITLE
Issues when translation locale and target locale don't match exactly

### ISSUE THREAD

**Issue by Stadly** [guillaumepotier/gettext.js#54]
There are issues when the translation locale and the target locale do not match perfectly. For instance, if the translations are in the locale `fr_FR`, and the target locale is `fr`, strings are not localized.

What makes the matter worse, is that `fr-FR` and `fr_FR` are not considered the same locale. `fr-FR` should be used in the [`lang` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang), and `fr_FR` should be used in [gettext files](https://www.gnu.org/software/gettext/manual/gettext.html#Locale-Names). Currently, this will lead to strings not being localized.

Here is a CodePen illustrating the issue: https://codepen.io/Stadly/pen/bGrozqa

**Comment by guillaumepotier** [comment]
Hi there,

Thanks *a lot* for this issue and the associated codepen <3

I didn't dig enough back in the time into locale codes. Could you explain me why there are two different syntaxes, with `-` or `_` ? Doesn't that follow the same ISO codes?

I could fairly easily manage to match `_` and `-` like I did in that codepen : https://codepen.io/guillaumepotier/pen/mdMpWEQ if not critical to add something like that in the code `locale = locale.replace('-', '_');`

Let me know

**Comment by Stadly** [comment]
Gettext uses the same locale format as POSIX, while the `lang` attribute uses BCP 47.

From [Wikipedia](https://en.wikipedia.org/wiki/Locale_(computer_software)):

> On POSIX platforms, locale identifiers are defined by ISO/IEC 15897, which is similar to the BCP 47 definition of language tags, but the locale variant modifier is defined differently, and the character set is included as a part of the identifier.

The locale identifiers in Gettext might look like `de`, `de_DE`, `de_DE@euro`, `de_DE.UTF-8`. I suggest stripping everything after `@` or `.`, and converting `_` to `-`. Then you should have the same format as the `lang` attribute.
