### ISSUE TITLE
node.js error

### ISSUE THREAD

**Issue by cyberthom** [guillaumepotier/gettext.js#7]
I am getting an error when trying to use this in node.js:

```
/node_modules/gettext.js/lib/gettext.js:10
      locale: document.documentElement.getAttribute('lang') || 'en',
              ^

ReferenceError: document is not defined
```

Looking through the source I'm a bit confused if this ever worked in node.js since it doesn't have a `document` object:
https://github.com/guillaumepotier/gettext.js/blob/master/lib/gettext.js#L10

Can this be removed? Not sure if a default based on browser information is sensible for an isomorphic library.

**Comment by marrobins** [comment]
I'm having the same issue. Isomorphic libraries should not assume that the DOM is available, as this will cause exceptions on pure Node apps.

**Comment by guillaumepotier** [comment]
I'd be glad to accept a PR that test if `window` or `document` is present and avoid this error on node :)

Best
