### ISSUE TITLE
Packaged po2json creates empty translations in .json when the string has no translation in .po file and nplurals=1

### ISSUE THREAD

**Issue by gbtami** [guillaumepotier/gettext.js#79]
Because of this ngettext() will return "" instead of English original.

Example .po and generated .json where Thai having translation in .po
```
#: ../client/clock.ts:29 ../client/view.ts:120
msgid "%1 day"
msgid_plural "%1 days"
msgstr[0] "%1 วัน"

    "%1 day": [
        "%1 วัน"
    ],
```

Example .po and generated .json where Chinese having no translation in .po
```
#: ../client/clock.ts:29 ../client/view.ts:120
msgid "%1 day"
msgid_plural "%1 days"
msgstr[0]
 
   "%1 day": [
        ""
    ],
```

**Comment by guillaumepotier** [comment]
Hello,

Thanks for raising this issue.

For your information, I'm not developing nor maintaining the po2json script. I think you should look its documentation here https://github.com/mikeedwards/po2json and maybe use the `--fallback-to-msgid` option?

I'm not sure it is a good idea to implement into `gettext` a check for empty string and replace by template default string if empty.

Let me know

Best

**Comment by gbtami** [comment]
You already package po2json into gettext.js
https://github.com/guillaumepotier/gettext.js/blob/master/bin/po2json
